[[redirects]]
from = "/api/*"
  to = "http://donipop.com:8080/api/:splat"  
  status = 200
  force = true

[[redirects]]
from = "/img/*"
  to = "http://donipop.com:3333/img/:splat"  
  status = 200
  force = true

[[redirects]]
from = "/*"
    to = "/index.html"
    status = 200